apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  labels:
    app: mysql
data:
  my.cnf: |
    [mysqld]
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
    default-authentication-plugin=mysql_native_password
    max_connections=200
    innodb_buffer_pool_size=1G
    innodb_log_file_size=256M
    slow_query_log=1
    long_query_time=2
    [client]
    default-character-set=utf8mb4

